//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FUJI.SyncFeed2.Servicio.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_DET_Estudio
    {
        public int intDetEstudioID { get; set; }
        public Nullable<int> intEstudioID { get; set; }
        public Nullable<int> intEstatusID { get; set; }
        public string vchNameFile { get; set; }
        public Nullable<int> intSizeFile { get; set; }
        public string vchPathFile { get; set; }
        public Nullable<System.DateTime> datFecha { get; set; }
        public string vchStudyInstanceUID { get; set; }
    
        public virtual tbl_MST_Estudio tbl_MST_Estudio { get; set; }
    }
}
