//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FUJI.SyncFeed2.Servicio.databaseLocal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NAPOLEONAUXEntities : DbContext
    {
        public NAPOLEONAUXEntities()
            : base("name=NAPOLEONAUXEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_CAT_EstatusAUX> tbl_CAT_EstatusAUX { get; set; }
        public DbSet<tbl_CAT_ModalidadAUX> tbl_CAT_ModalidadAUX { get; set; }
        public DbSet<tbl_ConfigSitioAUX> tbl_ConfigSitioAUX { get; set; }
        public DbSet<tbl_DET_EstudioAUX> tbl_DET_EstudioAUX { get; set; }
        public DbSet<tbl_MST_EstudioAUX> tbl_MST_EstudioAUX { get; set; }
    }
}
