//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FUJI.SyncFeed2.Servicio.databaseLocal
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CAT_ModalidadAUX
    {
        public tbl_CAT_ModalidadAUX()
        {
            this.tbl_MST_EstudioAUX = new HashSet<tbl_MST_EstudioAUX>();
        }
    
        public int intModalidadID { get; set; }
        public string vchModalidadClave { get; set; }
        public string vchModalidadDesc { get; set; }
        public Nullable<System.DateTime> datFecha { get; set; }
        public Nullable<bool> bitActivo { get; set; }
    
        public virtual ICollection<tbl_MST_EstudioAUX> tbl_MST_EstudioAUX { get; set; }
    }
}
